### ISSUE TITLE
Parsing ongoing PGN game where no move was made yet throws `java.lang.IllegalArgumentException: Invalid moves: *`

### ISSUE THREAD

**Issue by JoeyDP** [ctabin/jchess#36]
This line assumes the move list always starts with `1.`:
https://github.com/ctabin/jchess/blob/e3228122213e09cdbc26399b448d8e20452527d2/src/main/java/ch/astorm/jchess/io/PGNReader.java#L164

Unfortunately when no move was played yet, this is not the case (only the result is repeated, typically * for a game that was just started, but can be anything technically). Can this be fixed?

I am using this library to store chess games played in Minecraft and this requires storing metadata of the game (players, date, etc.) while no move was made yet.

**Comment by ctabin** [comment]
Hi @JoeyDP,

Can you provide a sample PNG with your case ? Thanks.

**Comment by JoeyDP** [comment]
Thank you for the quick reply!

I created a draft PR #37 with new tests that I think should pass. I'm still learning about the PGN standard so please feel free to check whether they make sense.

**Comment by ctabin** [comment]
Fixed by #37.
